services:
  - type: web
    name: mhnet-atendimento
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://lukasilverio94_db_user:7wf153@topidosespeciais.w7givnv.mongodb.net/?retryWrites=true&w=majority&appName=topidosespeciais
      - key: SECRET_KEY
        value: mhnet-secret-key-2025
